# This is a basic workflow to help you get started with Actions

name: Release Homebrew

# Controls when the action will run.
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  release:
    types: # This configuration does not affect the page_build event above
      - created

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Update Homebrew Formula
        uses: izumin5210/action-homebrew-tap@v1.0.0
        with:
          tap: MBoxPlus/homebrew-tap
          token: ${{ secrets.GITHUB_TOKEN }}
          tap-token: ${{ secrets.GITHUB_TOKEN }}
          release-branch: master
          formula: Formula/mbox

